---
name: Tests

on:
  push:
    branches:
      - '!*'
      - '!gh-pages'
      - 'master'
    tags:
      - v*
  pull_request:
    branches:
      - '*'

jobs:
  lint-client:
    name: Lint Client-side code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/cache@v1
        name: Cache npm modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint JS
        run: npm run lint:js
      - name: Lint Styles
        run: npm run lint:styles
  lint-php:
    name: Lint PHP code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        name: Cache composer vendor/ lib
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install
      - name: Lint PHP
        run: composer lint
